Update installation instruction for `probe-rs`
nrf-rs/microbit pull request #148
Opened 2024-06-07 19:26 UTC by OrangeTux

The binary `probe-rs` tools has been moved to it's own crate: `probe-rs-tools`. Therefore, the current instructions are outdated and fail:

```bash
$ cargo install probe-rs
    Updating crates.io index
  Downloaded probe-rs v0.24.0
  Downloaded 1 crate (1.7 MB) in 0.35s
error: there is nothing to install in `probe-rs v0.24.0`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency to a Cargo project with `cargo add`.
```

This commit updates the installation instruction.
For more information, see the [probe-rs' changelog][^1].

[^1]: https://github.com/probe-rs/probe-rs/blob/master/CHANGELOG.md#0240

2024-06-08 00:07 UTC, BartMassey requested changes
Could you please squash these changes and then force-push the result? Thanks much!

2024-06-08 00:11 UTC, BartMassey commented
Sigh. Thanks much for the timely update. We'll get it merged shortly.

2024-06-08 08:41 UTC, OrangeTux commented
Sure, here you go.

2024-06-09 11:07 UTC, qwandor approved these changes

2024-06-09 14:02 UTC, BartMassey approved these changes
Thanks much!

2024-06-09 14:02 UTC, merged

2024-06-09 14:02 UTC, BartMassey commented
Appreciate your help with this.